### ISSUE TITLE
Exception from PolymerIncludeElement

### ISSUE THREAD

**Issue by EasonPai** [lejard-h/polymer_app_layout_templates#2]
Once when I switch page from Home to One, 

```
path changed => home
page changed => { name: Home, path: home, element: home-page, isDefault: true, menu: true, hideLeftNav: false, icon: null}
```

I get this exception. And page of One cannot be render onto screen as well.
How do you solve this problem?

```
Uncaught Unhandled exception:
type 'PolymerDom' is not a subtype of type 'HtmlElement' of 'function result'.
#0      PolymerIncludeElement.rootElement (package:polymer_include_element/polymer_include_element.dart:17:44)
#1      PolymerIncludeElement.element= (package:polymer_include_element/polymer_include_element.dart:27:24)
#2      _data.<anonymous closure> (http://localhost:63342/polymer-lab/web/index.bootstrap.initialize.dart:52:46056)
#3      _InstanceMirrorImpl.invokeSetter (package:reflectable/src/reflectable_transformer_based.dart:203:20)
#4      _setUpPropertyChanged.<anonymous closure> (package:polymer/init.dart:71:24)
  Polymer.Async._atEndOfMicrotask   
  window.MutationObserver.observe.characterData 
```

Thanks

**Comment by lejard-h** [comment]
You can try to update polymer to 1.0.0-rc.10 and reflectable to 0.5.1 and my package to 0.1.7, it should resolves this problem.

**Comment by EasonPai** [comment]
Thanks for the help, but still no luck.

This is my yaml settings:

```
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.1
  polymer: 1.0.0-rc.10
  reflectable: 0.5.1
  web_components: ^0.12.0
  polymer_app_layout_template: 0.1.7

transformers:
- web_components:
    entry_points: web/index.html
- reflectable:
    entry_points: web/index.bootstrap.initialize.dart
#    entry_points: web/index.dart
- $dart2js:
#    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions: ['--trust-type-annotations', '--trust-primitives', '--enable-experimental-mirrors']
```

When I test with Dartium, I get error 

```
GET http://localhost:63342/polymer-lab/web/index.bootstrap.initialize.dart 404 (Not Found)
```
